services:
  coturn:
    image: coturn/coturn:4.6.3
    restart: unless-stopped
    network_mode: host
    command:
      - -c
      - /etc/coturn/turnserver.conf
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
